---
- name: Create smb mount credentials
  template:
    src: ./templates/smb/.smbcredentials.template
    dest: ~/.smbcredentials
    mode: 0600

- name: Execute block as sudo
  become: yes
  block:
    - name: Install smb packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ smb_packages }}"

    - name: Make smb mount directory
      file:
        path: "{{ smbmount_where }}"
        state: directory
        mode: 0755

    - name: Create smb mount
      template:
        src: ./templates/smb/smbmount_name.mount.template
        dest:  "/etc/systemd/system/{{ smbmount_name }}.mount"
        mode: 0644

    - name: Publish / enable / start smb mount
      command: "{{ item }}"
      with_items:
        - "systemctl daemon-reload"
        - "systemctl enable {{ smbmount_name }}.mount"
        - "systemctl start {{ smbmount_name }}.mount"
