---
- name: Include private variables
  include_vars: private.yml

- name: Execute block as sudo
  become: yes
  block:
    - name: Upgrade all packages
      apt:
        force_apt_get: yes
        name: "*"
        state: latest
        update_cache: yes

    - name: Install packages
      apt:
        name="{{ item }}"
        state=latest
      with_items: "{{ xubuntu01_packages }}"

- name: Set vnc server password
  expect:
    command: vncserver :1
    responses:
      (?i)password: "{{ vnc_password }}"
      (?i)verify: "{{ vnc_password }}"
      (?i)would you like to enter a view-only password (y/n)?: "n"
#     creates: ~/.vnc/xstartup

# - name: Backup existing xstartup file
#   command: mv ~/.vnc/xstartup ~/.vnc/xstartup.bak

# - name: Insert new xstartup file
#   copy:
#     src: ./templates/vnc/xstartup.template
#     dest:  ~/.vnc/xstartup
#     mode: 0755

# - name: Execute block as sudo
#   become: yes
#   block:
#     - name: Create vnc service
#       template:
#         src: ./templates/vnc/vncserver@.service.template
#         dest: /etc/systemd/system/vncserver@.service

#     - name: Make system aware of vnc service
#       command: systemctl daemon-reload

#     - name: Enable vnc service
#       command: systemctl enable vncserver@0.service
