---
- name: Include private variables
  include_vars: private.yml

- name: Import vnc tasks
  import_tasks: 01_vnc.yml
  tags: vnc

# - name: Import smb tasks
#   import_tasks: 02_smb.yml
#   tags: smb

# - name: Import gnucash tasks
#   import_tasks: 03_gnucash.yml
#   tags: gnucash

# - name: Import vscode tasks
#   import_tasks: 04_vscode.yml
#   tags: vscode
